# Generated by Django 5.2.4 on 2025-08-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('url', models.URLField(unique=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
